---
title: "Obraz jest wart tysiąca słów"
subtitle: "pasywne i interaktywne wizualizacje w R"
author: "Julia Romanowska"
institute: "BIOS, UiB"
date: "25.11.2020"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(xaringanthemer)
style_solarized_light()
xaringanExtra::use_clipboard()
xaringanExtra::use_fit_screen()

library(flipbookr)
library(tidyverse)
```

class: left, inverse, bottom

# PLAN

## Wstęp - jak projektować grafikę?
## Krótko o ggplot2
## Interaktywne grafy
### na szybko
### i trochę wolniej / zaawansowane techniki

---



---

## Wstęp - jak projektować grafikę?

- 

---

class: inverse, left

## ggplot2 i rozszerzenia

---

```{r my_cars, include = FALSE}
cars %>%
  filter(speed > 4) %>%
  ggplot() +
  aes(x = speed) +
  aes(y = dist) + #BREAK
  geom_point(
    alpha = .8, #BREAK2
    color = "blue" #BREAK3
    ) + #BREAK
  aes(size = speed) #BREAK
```

`r chunk_reveal("my_cars", break_type = "auto")`

